User interface format
tdu-src/SRC_novel_game pull request #3
Opened 2024-06-01 13:11 UTC by 44yyp9

2024-06-01 13:40 UTC, Garume requested changes

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_1.ks
> +ツクリはポスターのデザイン案を見せる
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_1.ks
> +ツクリは少し修正を加えて見せる[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_2.ks
> +時間経過..[p]
zasuku

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_2.ks
> +時間経過..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +廊下からの聞き覚えのある声に振り向くと、ツクリとメモリが立っている[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +購買に移[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +（ざわざわ....[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +そこにはもはや列の概念はなく、険しい戦場が広がっている[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +人の波の間から、カレーパンを２つ掴んだ[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_4.ks
> +授業後、ツクリの創作活動のためにワカツキと一緒に資料写真を集めることになった[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_4.ks
> +教室に入って撮影の準備を終えると、自分は中世の彫刻顔負けのポーズを取り始めた[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +昼休み、ご飯を食べ終えてゆっくりしていると、ツクリが話しかけてきた[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +ツクリのキャラが一気に畳みかけ、敵を撃破した[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +メモリの采配でチームの体勢を立て直し、無事敵を撃破した[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +（主人公）さん、見てください！この、「すき焼きミルクシェイ[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +突如登場した、謎の缶ジュースです！一番の謎は、まったく味が想像できないところです[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +私が偶然見つけたんだ...これは味を確かめないと一生後悔する気がする..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +飲んでも一生後悔しそうだけど..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +さあ（主人公）さん！ここまで来たら運命共同体です！一緒に味を確かめましょう[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +三人で、購入したドリンクを一気にあおった[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +これは...強烈すぎる..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +これを味わえないなんてきっと後悔するよ[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +味わって後悔したくない..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +スカウトとツクリは購入した謎のドリンクを一気にあおった[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +これは...強烈すぎる..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +ひ、ひどいです... （主人公）さん...私たちの哀れな姿を楽しむために、私たちのことを見捨てたんですね..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +恨むよ...(主人公)..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +）「ねぇ、なんか聞こえない...[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +（キュィィィン...[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +これはどこでもおそうじくん Z！自動で色んなところを掃除してくれる優れ者なんだよ[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +でもこの発明、まだまだ改良の余地があると思うんだよね...何かいい案ないかな[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +いい案か..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +ん～、まぁそうだよねぇ。とりあえず直してみる[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +とりあえずこれで大丈夫なはず[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +ん～、多分[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +多分って..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +それってイメチェンするってこと？面白そうだしやってみる[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +できた！流行りの感じにしてみたよ[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +これ、どこかで見たような..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +その後学校中に、校内を徘徊するガ〇ダムの都市伝説が広まるのであった..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +授業が終わった後、めもりが話しかけてきた [p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +昔この学校で、病気で亡くなっちゃった学生がいてね、科学部だったらしいんだ..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +めもり（通常）「ここが理科準備室だよ！[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ぶ、不気味だなぁ..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +急に入り口の扉が大きな音を立てて閉まった[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +それと同時に掃除用具入れが音を立てながら揺れ始める[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +も～！噂だから気になるんでしょ！来てくれないと成り立たないよ[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +あっ...成り立たないていうか...うまくいかないっていうか..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +うぐ..[p]
修正ポイント

2024-06-01 13:40 UTC, Garume commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ゴ、ゴメンナサイ..[p]
修正ポイント

2024-06-01 14:22 UTC, zasuku requested changes

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_2.ks
> +(さて、掃除を始めよう!)[p]
()消してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_2.ks
> +（みんな、掃除お疲れ様！）[p]
（）消してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_2.ks
> +時間をかけた甲斐もあって、教室はピカピカだ[p]
最後！付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ゴ、ゴメンナサイ..[p]
点.付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +もしかして、何か企んでた[p]
最後?付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +うぐ..[p]
点.ください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +うまくいかない[p]
？

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +あっ...成り立たないていうか...うまくいかないっていうか..[p]
点.足りないです

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +成り立たない[p]
？付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +も～！噂だから気になるんでしょ！来てくれないと成り立たないよ[p]
！付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +いや～、（主人公）の驚いた顔最高だよ！噂なんて作り話に決まっ...て..[p]
.点ください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +め、めもり...[p]
？

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +うわぁっ！[p]
？！にしてください最後

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ドッキリ大成功！！驚いた？！驚いた？[p]
最後！

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +バンッ！[p]
（）付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ガタガタッ！[p]
（）付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +それと同時に掃除用具入れが音を立てながら揺れ始める[p]
始めた！にしてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ガタガタガタッ！[p]
（）付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +？[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +急に入り口の扉が大きな音を立てて閉まった[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ガタンッ！[p]
（）付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ぶ、不気味だなぁ..[p]
.点入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +めもり（通常）「ここが理科準備室だよ！[p]
めもり（通常）「消してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +（主人公）も気になるでしょ！実際に確かめに行くよ[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +昔この学校で、病気で亡くなっちゃった学生がいてね、科学部だったらしいんだ..[p]
.入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +何それ[p]
？入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +ねぇ、知ってる?理科準備室の怖～いうわさ..[p]
.点入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_8.ks
> +授業が終わった後、めもりが話しかけてきた [p]
。入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +その後学校中に、校内を徘徊するガ〇ダムの都市伝説が広まるのであった..[p]
.点入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +これ、どこかで見たような..[p]
.点入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +できた！流行りの感じにしてみたよ[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +トントンカンカン[p]
（）入れて！付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +それってイメチェンするってこと？面白そうだしやってみる[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +ん～、多分[p]
？入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +多分って..[p]
.入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +はずって.... 本当に大丈夫...[p]
？入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +とりあえずこれで大丈夫なはず[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +ん～、まぁそうだよねぇ。とりあえず直してみる[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +トントンカンカン[p]
（）つけて！付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +いい案か..[p]
最後.点入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +でもこの発明、まだまだ改良の余地があると思うんだよね...何かいい案ないかな[p]
最後？入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +安全性は優れてないけど..[p]
最後.足りないです

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +これはどこでもおそうじくん Z！自動で色んなところを掃除してくれる優れ者なんだよ[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +大丈夫...でもこの機械はいったい何...[p]
？最後入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +大丈夫？！ケガしなかった？[p]
！最後入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +キキキキィィ！！！[p]
（）入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +ちょっ...！何あれ?[p]
！最後入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +ギュイイイイイン！！！！！！[p]
（）入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +キュィィイン...[p]
（）入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +（キュィィィン...[p]
）入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_7.ks
> +）「ねぇ、なんか聞こえない...[p]
）「消して？最後入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +ひ、ひどいです... （主人公）さん...私たちの哀れな姿を楽しむために、私たちのことを見捨てたんですね..[p]
最後.入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +恨むよ...(主人公)..[p]
最後.入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +えぇ..[p]
最後.入れてください #

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +これは...強烈すぎる..[p]
最後,足りないです

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +せーのっ[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +スカウトとツクリは購入した謎のドリンクを一気にあおった[p]
あおった→飲んだ！にしてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +もう（主人公）さんなんてほっときましょう！いきますよ、ツクリさん[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +味わって後悔したくない..[p]
最後   したくないんだけど...にしてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +これを味わえないなんてきっと後悔するよ[p]
最後...入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +かぁ～～！！意気地なしですね！（主人公）さん[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +これは...強烈すぎる..[p]
.点入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +三人で、購入したドリンクを一気にあおった[p]
あおった→飲んだ！にしてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +そう言ってくれるってわかってたよ... さあ、一緒に確かめよう...[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +流石ですね！（主人公）さん[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +さあ（主人公）さん！ここまで来たら運命共同体です！一緒に味を確かめましょう[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +飲んでも一生後悔しそうだけど..[p]
.一個足りないです

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +私が偶然見つけたんだ...これは味を確かめないと一生後悔する気がする..[p]
.一個足りないです

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +突如登場した、謎の缶ジュースです！一番の謎は、まったく味が想像できないところです[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_6.ks
> +（主人公）さん、見てください！この、「すき焼きミルクシェイ[p]
最後途切れてます。「すき焼きミルクシェイク」を！　です

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +
三人は無事マジックスクランブルの沼にはまり、毎晩の日課になった...　の文章入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +（勝った！）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +メモリの采配でチームの体勢を立て直し、無事敵を撃破した[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +（三人は無事マジックスクランブルの沼にはまり、毎晩の日課になった...[p]
（外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +（勝った！）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +ズドドドド！！[p]
（）付けてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +次の行動を決めなければ[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +（右の敵倒した！）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +（時間経過[p]
文消して時間経過カットイン入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +（やってみる！）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_5.ks
> +昼休み、ご飯を食べ終えてゆっくりしていると、ツクリが話しかけてきた[p]
。入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_4.ks
> +（どんどん撮っていこう！）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_4.ks
> +教室に入って撮影の準備を終えると、自分は中世の彫刻顔負けのポーズを取り始めた[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_4.ks
> +（学園のマスコットとの触れ合いで、ツクリのインスピレーションを刺激できた！[p]
（外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_4.ks
> +驚かさないように様子を窺っていると、猫は自分から近づいてきた[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_4.ks
> +（時間経過...[p]
時間経過カットインいれて文消してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_4.ks
> +授業後、ツクリの創作活動のためにワカツキと一緒に資料写真を集めることになった[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +（えっ、いいの？）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +廊下からの聞き覚えのある声に振り向くと、ツクリとメモリが立っている[p]
立っていた。にしてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +購買に移[p]
時間経過カットイン入れて、（背景：購買）にしてください　購買背景はdiscoの雑談に貼ったやつで

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +（ざわざわ....[p]
最後）入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +（はい、二人の分！）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +人の波の間から、クリームパンを２つ掴んだ[p]
！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +（パシッ！！[p]
）入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +(ここだ！)[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +.....やっぱそれ、（主人公）の分ね[p]
最後。入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +あっ...これ、私も分けなきゃいけない流れですか？めもり「.....やっぱそれ、（主人公）の分ね[p]
めもりのセリフ混ざってるので改行してください
最後。入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +（えっ、いいの？）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +（はい、二人の分！）[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +人の波の間から、カレーパンを２つ掴んだ[p]
最後！入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +（パシッ！！[p]
最後）入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +(ここだ！)[p]
（）外してください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +二人が行くには危険すぎる... 自分が行かなくては[p]
...最後入れてください

2024-06-01 14:22 UTC, zasuku commented on data/scenario/gakuen/tuzyo/gakuen_tuzyo_part_3.ks
> +そこにはもはや列の概念はなく、険しい戦場が広がっている[p]
...入れてください

2024-06-06 07:38 UTC, Garume approved these changes

2024-06-06 08:47 UTC, merged